/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Control;
import control.ControlDeFinestres;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Azzeddine Lakbir
 */
public class FinestraAfegirMoneda extends javax.swing.JDialog {

    /**
     * Creates new form FinestraAfegirMoneda2
     */
    public FinestraAfegirMoneda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }
     private ControlDeFinestres controlFinestres;
    private Control control;
    public JButton getjButtonAfegirMoneda() {
        return jButtonAfegirMoneda;
    }
    //Gets and setters
    public JTextField getjTextFieldNomMoneda() {
        return jTextFieldNomMoneda;
    }

    public JButton getjButtonTornar() {
        return jButtonTornar;
    }

    public JTextField getjTextFieldValorMoneda() {
        return jTextFieldValorMoneda;
        
    }

    public FinestraAfegirMoneda(ControlDeFinestres controlFinestres, Control control) {
       // this.setModal(true);
        this.controlFinestres = controlFinestres;
        this.control = control;
        this.setModal(true);
        initComponents();
        jButtonAfegirMoneda.addActionListener(control);
        jButtonTornar.addActionListener(control);
        this.setLocation(350, 150);
        this.setTitle("Afegir moneda");
      
       //control = new ControlConversor(this);
        
        //this.jButtonAfegirMoneda.addActionListener(control);
    }
    
    public void missatgeError(){
        JOptionPane.showMessageDialog(this,"Moneda afegida anteriorment", "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void missatgeConfirm(){
        JOptionPane.showMessageDialog(this,"Moneda afegida amb èxit", "Moneda afegida", 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomMoneda = new javax.swing.JTextField();
        jTextFieldValorMoneda = new javax.swing.JTextField();
        jLabeNomMoneda = new javax.swing.JLabel();
        jLabelValorMoneda = new javax.swing.JLabel();
        jButtonAfegirMoneda = new javax.swing.JButton();
        jButtonTornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Afegeix una moneda");

        jTextFieldNomMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomMonedaActionPerformed(evt);
            }
        });

        jLabeNomMoneda.setText("Nom de la moneda");

        jLabelValorMoneda.setText("Valor de la moneda");

        jButtonAfegirMoneda.setText("Afegir moneda");
        jButtonAfegirMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfegirMonedaActionPerformed(evt);
            }
        });

        jButtonTornar.setText("Tornar");
        jButtonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAfegirMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButtonTornar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabeNomMoneda)
                            .addComponent(jLabelValorMoneda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabeNomMoneda))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorMoneda))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAfegirMoneda)
                    .addComponent(jButtonTornar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomMonedaActionPerformed

    private void jButtonAfegirMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfegirMonedaActionPerformed

    }//GEN-LAST:event_jButtonAfegirMonedaActionPerformed

    private void jButtonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTornarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAfegirMoneda;
    private javax.swing.JButton jButtonTornar;
    private javax.swing.JLabel jLabeNomMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelValorMoneda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNomMoneda;
    private javax.swing.JTextField jTextFieldValorMoneda;
    // End of variables declaration//GEN-END:variables
}
