package Prog_Tarea09;

/**
*
* @author José Luis
* @version 9.1
*/
public class AplicacionCuentaBancaria extends javax.swing.JFrame {

   /** Creates new form AplicacionCuentaBancaria */
   public AplicacionCuentaBancaria() {
       initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

       jButton7 = new javax.swing.JButton();
       botonCuenta = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();
       jButton3 = new javax.swing.JButton();
       jButton4 = new javax.swing.JButton();
       jButton5 = new javax.swing.JButton();
       jButton6 = new javax.swing.JButton();
       jLabel1 = new javax.swing.JLabel();
       jButton8 = new javax.swing.JButton();
       jLabel2 = new javax.swing.JLabel();

       jButton7.setText("jButton7");

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Aplicación de Cuentas Bancarias");

       botonCuenta.setMnemonic('A');
       botonCuenta.setText("Abrir una cuenta nueva");
       botonCuenta.setToolTipText("Dar de alta una cuenta bancaria nueva");
       botonCuenta.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               botonCuentaActionPerformed(evt);
           }
       });

       jButton2.setMnemonic('l');
       jButton2.setText("Ver un listado de las cuentas disponibles");
       jButton2.setToolTipText("Listar las cuentas asignadas a los clientes");
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       jButton3.setMnemonic('d');
       jButton3.setText("Obtener los datos de una cuenta concreta");
       jButton3.setToolTipText("Datos completos de una cuenta");
       jButton3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton3ActionPerformed(evt);
           }
       });

       jButton4.setMnemonic('i');
       jButton4.setText("Realizar un ingreso en una cuenta");
       jButton4.setToolTipText("Ingresar un importe determinado en una cuenta bancaria");
       jButton4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton4ActionPerformed(evt);
           }
       });

       jButton5.setMnemonic('R');
       jButton5.setText("Retirar efectivo de una cuenta");
       jButton5.setToolTipText("Sacar dinero de una cuenta");
       jButton5.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton5ActionPerformed(evt);
           }
       });

       jButton6.setMnemonic('C');
       jButton6.setText("Consultar el saldo actual de una cuenta");
       jButton6.setToolTipText("Comprobar el saldo actual de una cuenta bancaria");
       jButton6.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton6ActionPerformed(evt);
           }
       });

       jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24));
       jLabel1.setForeground(new java.awt.Color(255, 0, 0));
       jLabel1.setText("Aplicación de Cuentas Bancarias");

       jButton8.setMnemonic('S');
       jButton8.setText("Salir de la aplicación");
       jButton8.setToolTipText("Salir de la aplicación");
       jButton8.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton8ActionPerformed(evt);
           }
       });

       jLabel2.setFont(new java.awt.Font("Tahoma", 2, 10));
       jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
       jLabel2.setText("(C) JFIC - José Luis Comesaña");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(layout.createSequentialGroup()
                       .addGap(55, 55, 55)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           .addComponent(botonCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                           .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
               .addContainerGap())
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(243, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(20, 20, 20)
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(botonCuenta)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton3)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton4)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton5)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton6)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jButton8)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
               .addComponent(jLabel2))
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents
   /**
    * Ir a retirada de efectivo
    * @param evt
    */
   private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Movimiento movimiento=new Movimiento(this,true,2);
       movimiento.setVisible(true);
   }//GEN-LAST:event_jButton5ActionPerformed

   /**
    * Salir de la aplicación
    * @param evt
    */
   private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       System.exit(0);
   }//GEN-LAST:event_jButton8ActionPerformed

   /**
    * Dar de alta nuevas cuentas
    * @param evt
    */
   private void botonCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuentaActionPerformed
       //this.setVisible(false);
       CuentaNueva cuentanueva=new CuentaNueva(this,true);
       cuentanueva.setVisible(true);
       //new CtaNueva().setVisible(true);
   }//GEN-LAST:event_botonCuentaActionPerformed

   /**
    * Mostrar todas las cuentas disponibles
    * @param evt
    */
   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Listados listado=new Listados(this,true);
       listado.setVisible(true);
   }//GEN-LAST:event_jButton2ActionPerformed

   /**
    * Mostrar los datos de una cuenta concreta
    * @param evt
    */
   private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Buscar buscar=new Buscar(this,true);
       buscar.setVisible(true);
   }//GEN-LAST:event_jButton3ActionPerformed

   /**
    * Ingresar efectivo en una cuenta
    * @param evt
    */
   private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Movimiento movimiento=new Movimiento(this,true,1);
       movimiento.setVisible(true);
   }//GEN-LAST:event_jButton4ActionPerformed

   /**
    * Ver el saldo de una cuenta
    * @param evt
    */
   private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Movimiento movimiento=new Movimiento(this,true,3);
       movimiento.setVisible(true);
   }//GEN-LAST:event_jButton6ActionPerformed

   /**
    * Apartado principal que pone en funcionamiento la aplicación
    * @param args 
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(AplicacionCuentaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(AplicacionCuentaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(AplicacionCuentaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(AplicacionCuentaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {

           public void run() {
               new AplicacionCuentaBancaria().setVisible(true);
           }
       });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton botonCuenta;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JButton jButton6;
   private javax.swing.JButton jButton7;
   private javax.swing.JButton jButton8;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   // End of variables declaration//GEN-END:variables
}

