package ejercicioSwing;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.JTextField;

public class EjercicioSwingMejorado extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	public EjercicioSwingMejorado() {
		initComponents();
	}

	/**
	 * Genera un n˙mero aleatorio entre dos numeros. Entre el minimo y el maximo
	 * incluidos
	 */
	private int generaNumeroAleatorio(int minimo, int maximo) {

		int num = (int) Math.floor(Math.random() * (minimo - (maximo + 1)) + (maximo + 1));
		return num;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		btnGenerar = new javax.swing.JButton();
		btnGenerar.setForeground(Color.BLUE);
		btnSalir = new javax.swing.JButton();
		btnSalir.setForeground(Color.RED);
		txtNumeroGenerado = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Generador de n\u00FAmeros");

		btnGenerar.setText("Generar");
		btnGenerar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnGenerarActionPerformed(evt);
			}
		});

		btnSalir.setText("Salir");
		btnSalir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				System.exit(1);
			}
		});

		txtNumeroGenerado.setEditable(false);

		jLabel1.setText("Principio");

		jLabel2.setText("Fin");

		jLabel3.setText("N\u00FAmero");

		JLabel lblEjercicioSwing = new JLabel();
		lblEjercicioSwing.setFont(new Font("Luminari", Font.PLAIN, 13));
		lblEjercicioSwing.setText("Ejercicio Swing");
		
		fin = new JTextField();
		fin.setColumns(10);
		
		principio = new JTextField();
		principio.setColumns(10);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(28)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel2)
						.addComponent(jLabel1)
						.addComponent(jLabel3))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(fin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(principio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtNumeroGenerado, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(73, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(44, Short.MAX_VALUE)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(lblEjercicioSwing, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
							.addComponent(btnGenerar)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btnSalir)))
					.addGap(81))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(22)
					.addComponent(lblEjercicioSwing)
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel1)
						.addComponent(principio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel2)
						.addComponent(fin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(37)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(txtNumeroGenerado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(32)
					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(btnGenerar)
						.addComponent(btnSalir))
					.addContainerGap(56, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGenerarActionPerformed

		int numero1 = 0, numero2 = 0;
		// Obtener valores
		try {
			numero1 = Integer.parseInt(principio.getText());
			numero2 = Integer.parseInt(fin.getText());
		// Caso de que no se introduzca nada...
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Debes introducir n˙meros");
		}
		// El segundo n˙mero no puede ser mayor que el primero
		if (numero1 > numero2) {
			JOptionPane.showMessageDialog(this, "El segundo ha de ser mayor que el primero");
		} else {
			// Pasa a string el n˙mero generado
			String numeroGenerado = String.valueOf(generaNumeroAleatorio(numero1, numero2));

			// Muestra n˙mero generado
			txtNumeroGenerado.setText(numeroGenerado);
		}

	}// GEN-LAST:event_btnGenerarActionPerformed

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EjercicioSwingMejorado.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EjercicioSwingMejorado.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EjercicioSwingMejorado.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EjercicioSwingMejorado.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EjercicioSwingMejorado().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnGenerar;
	private javax.swing.JButton btnSalir;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField txtNumeroGenerado;
	private JTextField fin;
	private JTextField principio;
}
