package Prog_Tarea07;

import javax.swing.JOptionPane;

/**
 *
 * @author José Luis Comesaña
 * @version 7.0
 */
public class JDTorneo extends javax.swing.JDialog {
    private boolean haPulsadoAceptar=false;
    
    /** 
     * Método que devuelve true si se ha pulsado el botón de Aceptar
     * 
     * @return 
     */
    public boolean isHaPulsadoAceptar(){
        return haPulsadoAceptar;
    }
    /**
     * Crea un nuevo formulario JDTorneo inicializando sus componentes y ocultando
     * el mensaje de error
     * @param <code>parent</code> De quién dependerá este formulario
     * @param <code>modal</code> true para sólo poder tocar este nivel mientras
     * esté abierto y false para poder acceder a niveles superiores
     */
    public JDTorneo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.textoError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        textoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AÑADIR NUEVO TORNEO");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("AÑADIR NUEVO TORNEO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Categoría:");

        textoNombre.setToolTipText("Nombre del torneo");
        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        textoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoNombreKeyTyped(evt);
            }
        });

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grand Slam", "ATP World Tour Master 1000", "ATP World Tour 500", "ATP World Tour 250" }));
        comboCategoria.setToolTipText("A qué categoría pertenece el torneo introducido");

        aceptar.setText("Aceptar");
        aceptar.setToolTipText("Memorizar los datos introducidos");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setToolTipText("Descartar los datos introducidos y salir a la pantalla principal");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        textoError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textoError.setForeground(new java.awt.Color(255, 0, 0));
        textoError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoError.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(textoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboCategoria, 0, 243, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 40, Short.MAX_VALUE)
                                        .addComponent(aceptar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelar)
                                        .addGap(47, 47, 47)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoError, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoError, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Si se pulsa cancelar se oculta esta pantalla volviendo a Principal sin
     * hacer nada
     * @param <code>evt</code> evento de clic en botón 'Cancelar' 
     */
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.haPulsadoAceptar=false;
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * Comprueba que se halla introducido algo en 'nombre' de torneo. 
     * Si es así, oculta esta pantalla y volvemos a Principal, en caso contrario
     * nos muestra un error indicándolo
     * @param <code>evt</code> evento de clic en el botón 'Aceptar'
     */
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if(!this.textoNombre.getText().equals("")){
            this.haPulsadoAceptar=true;
            this.setVisible(false);
        }else{
            this.textoError.setText("El nombre del torneo no puede estar vacío");
            this.textoError.setVisible(true);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * Cuando tecleamos algo en la caja de texto de 'Nombre' desaparece el mensaje
     * de error
     * @param <code>evt</code> evento de pulsación de tecla en la caja de texto 'Nombre'
     */ 
    private void textoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoNombreKeyTyped
        this.textoError.setVisible(false);
    }//GEN-LAST:event_textoNombreKeyTyped

    /**
     * Cuando pulsamos Intro estando sobre la caja de texto de 'Nombre' es igual
     * a haber pulsado sobre el botón de aceptar
     * @param <code>evt</code> evento de pulsar 'Intro' en caja de texto 'Nombre'
     */ 
    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        aceptarActionPerformed(evt);
    }//GEN-LAST:event_textoNombreActionPerformed

    /**
     * Devuelve el nombre del torneo y la puntuación obtenida dependiendo de la
     * categoría que tenga dicho torneo:
     * Comprueba si el valor seleccionado del comboBox es igual a alguno de los
     * valores introducidos en la clase Torneo
     * @return 
     */
    public Torneo getTorneo(){
        String nombre=this.textoNombre.getText();
        int puntuacion=0;
        String categoria = (String) this.comboCategoria.getSelectedItem();
        if(categoria.equalsIgnoreCase(Torneo.GRAND_SLAM)){
            puntuacion=2000;
        }else if(categoria.equalsIgnoreCase(Torneo.MASTER1000)){
            puntuacion=1000;
        }else if(categoria.equalsIgnoreCase(Torneo.MASTER500)){
            puntuacion=500;
        }else if(categoria.equalsIgnoreCase(Torneo.MASTER250)){
            puntuacion=250;
        }
        return new Torneo(nombre,puntuacion);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDTorneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDTorneo dialog = new JDTorneo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel textoError;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}

